name: deploy_node_app

on:
    push:
        branches: 
            - mern-ec2-docker

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
              
            - name: login to docker hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              
            - name: Build Docker Image
              run: docker build -t kaweeshamr/nodejs-app ./backend # Specify the context to backend

            - name: push Docker Image
              run: docker push kaweeshamr/nodejs-app:latest

    deploy:
      name: deploy-to-aws
      needs: build
      runs-on: self-hosted
      env:  # Define environment variables here
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        PORT: 3002
        jwt_secret: ${{ secrets.jwt_secret }}
      steps:
        - name: pull image from docker hub
          run: docker pull kaweeshamr/nodejs-app:latest
      
        - name: run container
          run: docker run -d -p 3002:3002 --name nodejs-app-container \
            -e MONGODB_URI \
            -e PORT \
            -e jwt_secret \
            kaweeshamr/nodejs-app:latest
